export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const FETCH_COMMENTS_REQUST = "FETCH_COMMENTS_REQUST";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_FAILURE = "FETCH_COMMENTS_FAILURE";
